services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - etl-network

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datawarehouse
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - etl-network

  # Service to initialize the database schema and create necessary tables
  db-init:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datawarehouse
    entrypoint: ["python", "-c", "from src.utils.storage_utils import init_database; init_database()"]
    networks:
      - etl-network
    restart: on-failure

  # Service to create MinIO buckets
  minio-init:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      SPARK_ENDPOINT_INTERNAL: http://minio:9000
      SPARK_ENDPOINT_EXTERNAL: http://localhost:9000
    entrypoint: ["python", "-c", "from src.utils.storage_utils import init_minio; init_minio()"]
    networks:
      - etl-network
    restart: on-failure

  # Main ETL application for AWS sales data
  aws-sales-etl:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      minio-init:
        condition: service_completed_successfully
      db-init:
        condition: service_completed_successfully
    environment:
      MINIO_ENDPOINT: minio:9000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datawarehouse
      SPARK_ENDPOINT_INTERNAL: http://minio:9000
      SPARK_ENDPOINT_EXTERNAL: http://localhost:9000
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    user: root  # Run as root to ensure write permissions
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    networks:
      - etl-network
    # Keep container running for manual execution
    restart: "no"

networks:
  etl-network:
    driver: bridge

volumes:
  minio-data:
  postgres-data: 